USE [master]
GO

/****** Object:  Database [YES]    Script Date: 06/28/2014 13:00:58 ******/
CREATE DATABASE [YES] ON  PRIMARY 
( NAME = N'YES', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\YES.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'YES_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\YES_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [YES] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [YES].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [YES] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [YES] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [YES] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [YES] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [YES] SET ARITHABORT OFF 
GO

ALTER DATABASE [YES] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [YES] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [YES] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [YES] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [YES] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [YES] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [YES] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [YES] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [YES] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [YES] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [YES] SET  DISABLE_BROKER 
GO

ALTER DATABASE [YES] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [YES] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [YES] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [YES] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [YES] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [YES] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [YES] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [YES] SET  READ_WRITE 
GO

ALTER DATABASE [YES] SET RECOVERY FULL 
GO

ALTER DATABASE [YES] SET  MULTI_USER 
GO

ALTER DATABASE [YES] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [YES] SET DB_CHAINING OFF 
GO


