//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yes.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class YesCourse
    {
        public YesCourse()
        {
            this.YesCourseFees = new HashSet<YesCourseFee>();
            this.YesStudents = new HashSet<YesStudent>();
        }
    
        public int CourseID { get; set; }
        public string CourseName { get; set; }
        public string CourseDescription { get; set; }
    
        public virtual ICollection<YesCourseFee> YesCourseFees { get; set; }
        public virtual ICollection<YesStudent> YesStudents { get; set; }
    }
}
