//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yes.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class YesDesignation
    {
        public YesDesignation()
        {
            this.YesEmployees = new HashSet<YesEmployee>();
        }
    
        public int DesignationID { get; set; }
        public string DesignationName { get; set; }
        public string DesignationDescription { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<YesEmployee> YesEmployees { get; set; }
    }
}
