//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yes.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class YesEmployee
    {
        public YesEmployee()
        {
            this.YesUsers = new HashSet<YesUser>();
        }
    
        public int EmployeeID { get; set; }
        public string EmployeeFirstName { get; set; }
        public string EmployeeMiddleName { get; set; }
        public string EmployeeLastName { get; set; }
        public Nullable<long> EmployeeMobileNo { get; set; }
        public Nullable<long> EmployeeAlternateMobileNo { get; set; }
        public string EmployeeEmailID { get; set; }
        public string EmployeeAddress1 { get; set; }
        public string EmployeeAddress2 { get; set; }
        public string EmployeeCity { get; set; }
        public string EmployeeDisctrict { get; set; }
        public string EmployeeState { get; set; }
        public Nullable<int> EmployeePinCode { get; set; }
        public Nullable<int> DesignationID { get; set; }
    
        public virtual YesDesignation YesDesignation { get; set; }
        public virtual ICollection<YesUser> YesUsers { get; set; }
    }
}
