//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yes.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class YesEmployee
    {
        public YesEmployee()
        {
            this.YesUsers = new HashSet<YesUser>();
        }
    
        public int EmployeeID { get; set; }
        public string EmployeeFirstName { get; set; }
        public string EmployeeMiddleName { get; set; }
        public string EmployeeLastName { get; set; }
        public string EmployeeMobileNo { get; set; }
        public string EmployeeAlternateMobileNo { get; set; }
        public string EmployeeEmailID { get; set; }
        public string EmployeeAddress1 { get; set; }
        public string EmployeeAddress2 { get; set; }
        public string EmployeeCity { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<int> EmployeePinCode { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual YesDesignation YesDesignation { get; set; }
        public virtual YesDistrict YesDistrict { get; set; }
        public virtual YesSchool YesSchool { get; set; }
        public virtual ICollection<YesUser> YesUsers { get; set; }
    }
}
