//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yes.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class YesFee
    {
        public YesFee()
        {
            this.YesCourseFees = new HashSet<YesCourseFee>();
        }
    
        public int FeeID { get; set; }
        public string FeeName { get; set; }
        public string FeeDescription { get; set; }
        public Nullable<decimal> FeeAmount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<YesCourseFee> YesCourseFees { get; set; }
    }
}
