//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yes.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class YesParent
    {
        public YesParent()
        {
            this.YesStudents = new HashSet<YesStudent>();
        }
    
        public int ParentID { get; set; }
        public string ParentFirstName { get; set; }
        public string ParentMiddleName { get; set; }
        public string ParentLastName { get; set; }
        public Nullable<long> ParentMobileNo { get; set; }
        public Nullable<long> ParentAlternateMobileNo { get; set; }
        public string ParentEmailID { get; set; }
        public string ParentAddress1 { get; set; }
        public string ParentAddress2 { get; set; }
        public string ParentCity { get; set; }
        public string ParentDisctrict { get; set; }
        public string ParentState { get; set; }
        public Nullable<int> ParentPinCode { get; set; }
        public string ParentOccupation { get; set; }
    
        public virtual ICollection<YesStudent> YesStudents { get; set; }
    }
}
