//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yes.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class YesSubject
    {
        public YesSubject()
        {
            this.YesStudentSubjectMaps = new HashSet<YesStudentSubjectMap>();
        }
    
        public int SubjectID { get; set; }
        public string SubjectName { get; set; }
        public short SubjectMarks { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<YesStudentSubjectMap> YesStudentSubjectMaps { get; set; }
    }
}
