//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yes.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class YesStudent
    {
        public int StudentID { get; set; }
        public string StudentFirstName { get; set; }
        public string StudentMiddleName { get; set; }
        public string StudentLastName { get; set; }
        public Nullable<int> StudentRollNumber { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> CourseID { get; set; }
    
        public virtual YesCourse YesCourse { get; set; }
        public virtual YesParent YesParent { get; set; }
    }
}
