//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yes.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class YesStudent
    {
        public YesStudent()
        {
            this.YesStudentSubjectMaps = new HashSet<YesStudentSubjectMap>();
        }
    
        public int StudentID { get; set; }
        public string StudentFirstName { get; set; }
        public string StudentMiddleName { get; set; }
        public string StudentLastName { get; set; }
        public int StudentRollNumber { get; set; }
        public Nullable<System.DateTime> StudentDOB { get; set; }
        public string StudentGender { get; set; }
        public int ParentID { get; set; }
        public int CourseID { get; set; }
        public int SchoolID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual YesCourse YesCourse { get; set; }
        public virtual YesParent YesParent { get; set; }
        public virtual YesSchool YesSchool { get; set; }
        public virtual ICollection<YesStudentSubjectMap> YesStudentSubjectMaps { get; set; }
    }
}
