//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yes.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class YesSchool
    {
        public YesSchool()
        {
            this.YesEmployees = new HashSet<YesEmployee>();
            this.YesStudents = new HashSet<YesStudent>();
        }
    
        public int SchoolID { get; set; }
        public string SchoolName { get; set; }
        public string SchoolAddress1 { get; set; }
        public string SchoolAddress2 { get; set; }
        public Nullable<int> SchoolEstiblishmentYear { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<YesEmployee> YesEmployees { get; set; }
        public virtual ICollection<YesStudent> YesStudents { get; set; }
    }
}
