//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yes.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class YesStudentSubjectMap
    {
        public YesStudentSubjectMap()
        {
            this.YesStudentMarks = new HashSet<YesStudentMark>();
        }
    
        public int StudentSubjectID { get; set; }
        public int StudentID { get; set; }
        public int SubjectID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual YesStudent YesStudent { get; set; }
        public virtual ICollection<YesStudentMark> YesStudentMarks { get; set; }
        public virtual YesSubject YesSubject { get; set; }
    }
}
