//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yes.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class YesStudentMark
    {
        public int StudentMarksID { get; set; }
        public int StudentSubjectID { get; set; }
        public int ExamTypeID { get; set; }
        public short ObtainedMarks { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual YesExamType YesExamType { get; set; }
        public virtual YesStudentSubjectMap YesStudentSubjectMap { get; set; }
    }
}
