//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yes.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class YesState
    {
        public YesState()
        {
            this.YesDistricts = new HashSet<YesDistrict>();
        }
    
        public int StateID { get; set; }
        public string StateName { get; set; }
        public string StateDescription { get; set; }
    
        public virtual ICollection<YesDistrict> YesDistricts { get; set; }
    }
}
