//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yes.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class YesUser
    {
        public YesUser()
        {
            this.YesUserPrivileges = new HashSet<YesUserPrivilege>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public Nullable<short> FalseLoginCount { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual YesEmployee YesEmployee { get; set; }
        public virtual ICollection<YesUserPrivilege> YesUserPrivileges { get; set; }
    }
}
